[CmdletBinding()]
param(
    [string]$Prefix = (Join-Path (Get-Location) "install\windows-msvc"),
    [string]$VcpkgRoot = (Join-Path (Get-Location) "build\vcpkg"),
    [string]$VcpkgTriplet = "x64-windows",
    [ValidateSet("win32")]
    [string]$Target = "win32",
    [switch]$BundledDependencies
)

$ErrorActionPreference = "Stop"

function Convert-ToFullPath {
    param([string]$Path)

    $executionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($Path)
}

function Convert-ToSingleQuotedLiteral {
    param([string]$Value)

    $Value.Replace("'", "''")
}

function Write-PowerShellScript {
    param(
        [string]$Path,
        [string]$Contents
    )

    $normalized = $Contents -replace "`r`n", "`n"
    $normalized = $normalized -replace "`r", ""
    $normalized = ($normalized.TrimEnd() + "`n") -replace "`n", "`r`n"
    [System.IO.File]::WriteAllText(
        $Path,
        $normalized,
        [System.Text.UTF8Encoding]::new($false))
}

function Get-RubyConfigValue {
    param([string]$Name)

    $value = & ruby -rrbconfig -e "print RbConfig::CONFIG.fetch(ARGV.fetch(0))" $Name
    if ($LASTEXITCODE -ne 0) {
        throw "ruby failed while reading RbConfig::CONFIG[$Name]"
    }
    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "Ruby configuration value is empty: $Name"
    }

    $value
}

$Prefix = Convert-ToFullPath $Prefix
$runtimeVcpkgPrefix = ""
if ($BundledDependencies) {
    $VcpkgRoot = ""
    $bundledVcpkgPrefix = Join-Path $Prefix "vcpkg"
    if (-not (Test-Path -LiteralPath $bundledVcpkgPrefix -PathType Container)) {
        throw "Missing bundled development dependencies: $bundledVcpkgPrefix"
    }
    $VcpkgPrefix = ""
} else {
    $VcpkgRoot = Convert-ToFullPath $VcpkgRoot
    $VcpkgPrefix = Join-Path $VcpkgRoot "installed\$VcpkgTriplet"
    if (-not (Test-Path -LiteralPath $VcpkgPrefix -PathType Container)) {
        throw "Missing vcpkg installed prefix: $VcpkgPrefix"
    }
    $runtimeVcpkgPrefix = $VcpkgPrefix
}

New-Item -ItemType Directory -Force -Path $Prefix | Out-Null

$vcpkgRootLiteral = Convert-ToSingleQuotedLiteral $VcpkgRoot
$vcpkgPrefixLiteral = Convert-ToSingleQuotedLiteral $VcpkgPrefix
$runtimeVcpkgPrefixLiteral = Convert-ToSingleQuotedLiteral $runtimeVcpkgPrefix
$targetLiteral = Convert-ToSingleQuotedLiteral $Target
$tripletLiteral = Convert-ToSingleQuotedLiteral $VcpkgTriplet
$rubyVersionLiteral = Convert-ToSingleQuotedLiteral (
    Get-RubyConfigValue -Name "ruby_version")
$rubyArchLiteral = Convert-ToSingleQuotedLiteral (
    Get-RubyConfigValue -Name "arch")

$runtimeTemplate = @'
# Generated by orocos-rock/tools/export-windows-env.ps1.
# Dot-source this file from PowerShell: . .\env.ps1

& {
    param(
        [string]$Prefix,
        [string]$VcpkgPrefix,
        [string]$Target
    )

    function Set-OrocosRockPathEntries {
        param(
            [string]$Name,
            [string[]]$Values
        )

        $availableValues = @(
            $Values | Where-Object {
                Test-Path -LiteralPath $_ -PathType Container
            }
        )
        $current = [Environment]::GetEnvironmentVariable($Name, "Process")
        $existing = if ([string]::IsNullOrWhiteSpace($current)) {
            @()
        } else {
            @($current -split [regex]::Escape([IO.Path]::PathSeparator))
        }

        $seen = [Collections.Generic.HashSet[string]]::new(
            [StringComparer]::OrdinalIgnoreCase)
        $combined = [Collections.Generic.List[string]]::new()
        foreach ($entry in @($availableValues) + @($existing)) {
            if (-not [string]::IsNullOrWhiteSpace($entry) -and
                $seen.Add($entry)) {
                [void]$combined.Add($entry)
            }
        }

        [Environment]::SetEnvironmentVariable(
            $Name,
            ($combined -join [IO.Path]::PathSeparator),
            "Process")
    }

    $orocosDirectory = Join-Path $Prefix "lib\orocos"
    $targetOrocosDirectory = Join-Path $orocosDirectory $Target
    $installedOrocosDirectories = if (
        Test-Path -LiteralPath $orocosDirectory -PathType Container
    ) {
        @(Get-ChildItem -LiteralPath $orocosDirectory -Directory -Recurse |
            ForEach-Object FullName)
    } else {
        @()
    }
    $componentDirectories = @(
        $targetOrocosDirectory,
        (Join-Path $targetOrocosDirectory "ocl"),
        (Join-Path $targetOrocosDirectory "ocl\plugins"),
        (Join-Path $targetOrocosDirectory "plugins"),
        (Join-Path $targetOrocosDirectory "types"),
        (Join-Path $targetOrocosDirectory "rtt_opcua\plugins")
    ) + $installedOrocosDirectories + @($orocosDirectory)
    $runtimeDirectories = @(
        (Join-Path $Prefix "bin"),
        (Join-Path $Prefix "lib"),
        (Join-Path $Prefix "lib\typelib"),
        $orocosDirectory,
        (Join-Path $targetOrocosDirectory "ocl"),
        (Join-Path $targetOrocosDirectory "ocl\plugins"),
        (Join-Path $targetOrocosDirectory "ocl\types"),
        (Join-Path $targetOrocosDirectory "plugins"),
        (Join-Path $targetOrocosDirectory "types"),
        (Join-Path $targetOrocosDirectory "rtt_opcua\plugins")
    ) + $installedOrocosDirectories
    if (-not [string]::IsNullOrWhiteSpace($VcpkgPrefix)) {
        $runtimeDirectories += Join-Path $VcpkgPrefix "bin"
    }
    $pkgConfigDirectory = Join-Path $Prefix "lib\pkgconfig"
    $typelibPluginDirectory = Join-Path $Prefix "lib\typelib"

    $env:OROCOS_PREFIX = $Prefix
    $env:OROCOS_TARGET = $Target
    $env:PKG_CONFIG_LIBDIR = $pkgConfigDirectory
    Set-OrocosRockPathEntries -Name "PATH" -Values $runtimeDirectories
    Set-OrocosRockPathEntries `
        -Name "RTT_COMPONENT_PATH" -Values $componentDirectories
    Set-OrocosRockPathEntries `
        -Name "PKG_CONFIG_PATH" -Values @($pkgConfigDirectory)
    Set-OrocosRockPathEntries `
        -Name "TYPELIB_PLUGIN_PATH" -Values @($typelibPluginDirectory)
    Set-OrocosRockPathEntries -Name "CMAKE_PREFIX_PATH" -Values @($Prefix)
} $PSScriptRoot '@VCPKG_PREFIX@' '@TARGET@'
'@

$developmentTemplate = @'
# Generated by orocos-rock/tools/export-windows-env.ps1.
# Dot-source this file from PowerShell: . .\dev-env.ps1

. (Join-Path $PSScriptRoot "env.ps1")

& {
    param(
        [string]$Prefix,
        [string]$VcpkgRoot,
        [string]$VcpkgPrefix,
        [string]$VcpkgTriplet,
        [string]$RubyVersion,
        [string]$RubyArch
    )

    function Set-OrocosRockPathEntries {
        param(
            [string]$Name,
            [string[]]$Values
        )

        $availableValues = @(
            $Values | Where-Object {
                Test-Path -LiteralPath $_ -PathType Container
            }
        )
        $current = [Environment]::GetEnvironmentVariable($Name, "Process")
        $existing = if ([string]::IsNullOrWhiteSpace($current)) {
            @()
        } else {
            @($current -split [regex]::Escape([IO.Path]::PathSeparator))
        }
        $seen = [Collections.Generic.HashSet[string]]::new(
            [StringComparer]::OrdinalIgnoreCase)
        $combined = [Collections.Generic.List[string]]::new()
        foreach ($entry in @($availableValues) + @($existing)) {
            if (-not [string]::IsNullOrWhiteSpace($entry) -and
                $seen.Add($entry)) {
                [void]$combined.Add($entry)
            }
        }

        [Environment]::SetEnvironmentVariable(
            $Name,
            ($combined -join [IO.Path]::PathSeparator),
            "Process")
    }

    if ([string]::IsNullOrWhiteSpace($VcpkgPrefix)) {
        $candidate = Join-Path $Prefix "vcpkg"
        if (Test-Path -LiteralPath $candidate -PathType Container) {
            $VcpkgPrefix = $candidate
        }
    }
    if ([string]::IsNullOrWhiteSpace($VcpkgRoot)) {
        [Environment]::SetEnvironmentVariable("VCPKG_ROOT", $null, "Process")
    } else {
        $env:VCPKG_ROOT = $VcpkgRoot
    }
    $env:VCPKG_DEFAULT_TRIPLET = $VcpkgTriplet
    $gemHome = Join-Path $Prefix "toolchain\gems"
    $env:GEM_HOME = $gemHome
    $rubyCommand = Get-Command ruby.exe -CommandType Application `
        -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($null -eq $rubyCommand) {
        throw "The Orocos development environment requires ruby.exe on PATH."
    }
    $developmentPathEntries = @(
        (Join-Path $Prefix "toolchain\bin"),
        (Split-Path -Parent $rubyCommand.Source)
    )
    if (-not [string]::IsNullOrWhiteSpace($VcpkgPrefix)) {
        $developmentPathEntries += Join-Path $VcpkgPrefix "debug\bin"
    }
    Set-OrocosRockPathEntries -Name "PATH" -Values $developmentPathEntries
    Set-OrocosRockPathEntries -Name "GEM_PATH" -Values @($gemHome)
    Set-OrocosRockPathEntries -Name "RUBYLIB" -Values @(
        (Join-Path $Prefix "lib\ruby\$RubyVersion"),
        (Join-Path $Prefix "lib\$RubyArch\ruby\$RubyVersion"),
        (Join-Path $Prefix "lib\ruby\$RubyVersion\$RubyArch")
    )
    $developmentPrefixes = @($Prefix)
    $pkgConfigDirectories = @(Join-Path $Prefix "lib\pkgconfig")
    if (-not [string]::IsNullOrWhiteSpace($VcpkgPrefix)) {
        $developmentPrefixes += $VcpkgPrefix
        $pkgConfigDirectories += Join-Path $VcpkgPrefix "lib\pkgconfig"
    }
    $env:PKG_CONFIG_LIBDIR = $pkgConfigDirectories -join [IO.Path]::PathSeparator
    Set-OrocosRockPathEntries `
        -Name "PKG_CONFIG_PATH" -Values $pkgConfigDirectories
    Set-OrocosRockPathEntries `
        -Name "CMAKE_PREFIX_PATH" -Values $developmentPrefixes
} $PSScriptRoot '@VCPKG_ROOT@' '@VCPKG_PREFIX@' '@VCPKG_TRIPLET@' `
    '@RUBY_VERSION@' '@RUBY_ARCH@'
'@

$runtimeScript = $runtimeTemplate.Replace(
    "@VCPKG_PREFIX@", $runtimeVcpkgPrefixLiteral).Replace(
    "@TARGET@", $targetLiteral)
$developmentScript = $developmentTemplate.Replace(
    "@VCPKG_ROOT@", $vcpkgRootLiteral).Replace(
    "@VCPKG_PREFIX@", $vcpkgPrefixLiteral).Replace(
    "@VCPKG_TRIPLET@", $tripletLiteral).Replace(
    "@RUBY_VERSION@", $rubyVersionLiteral).Replace(
    "@RUBY_ARCH@", $rubyArchLiteral)

$runtimePath = Join-Path $Prefix "env.ps1"
$developmentPath = Join-Path $Prefix "dev-env.ps1"
Write-PowerShellScript -Path $runtimePath -Contents $runtimeScript
Write-PowerShellScript -Path $developmentPath -Contents $developmentScript

Write-Host "Wrote $runtimePath"
Write-Host "Wrote $developmentPath"
